"""Generated by meridian-design's tools/generate_typed_operations.py from the matrix and the domain protos (spec/typed-sidecar-operations). Do not edit.

The operations a plugin performs, one per bus row its roles may publish.

A quantity is a Python Decimal (or an int) here and a meridian.v1.Decimal on
the wire: its integer, in two 64-bit halves, and the scale it was stated
with, which is the Decimal's own exponent -- 1.50 crosses as 150 at scale 2
and reads back as 1.50. An amount of currency is a Money, a Decimal and its
ISO 4217 code. Converted once, in this file, and refused rather than
rounded: a float, more than 18 decimal places, or more than 38 digits
(decisions/023).

A plugin that reads a venue converts to the platform's convention before
it calls anything here: amounts in the currency's major unit, quantities in
the instrument's own units. It keeps what the venue sent, as sent, in its
own logs. A float the venue sent becomes Decimal(repr(value)), its shortest
round-trip form, and never Decimal(value), its binary expansion.
"""

from __future__ import annotations

import base64
import re
from collections.abc import Awaitable, Callable, Sequence
from dataclasses import dataclass
from decimal import Decimal
from typing import TYPE_CHECKING, Any, TypeVar

from meridian.plugin.v1 import operations_pb2 as ops
from meridian.v1 import sidecar_pb2

if TYPE_CHECKING:
    from .receive import Heard

_Answer = TypeVar("_Answer")

# What the wire carries (decisions/023): a scale of 0 to 18, and an integer
# whose magnitude is below 10^38.
_MOST_PLACES = 18
_TOO_MANY_DIGITS = 10**38
_LOW_HALF = 2**64 - 1


@dataclass(frozen=True)
class Money:
    """An amount of currency: a Decimal (or an int) and its ISO 4217 code.

    One value rather than an amount with its currency beside it, so a call
    carrying amounts in two currencies cannot pair either with the wrong one.
    """

    amount: Decimal | int
    currency_code: str


def _decimal(value: Decimal | int, name: str) -> ops.Decimal:
    """A number as the wire carries it: its integer, in two 64-bit halves, and
    the scale it was stated with. Exact, or refused naming the field; never
    rounded, and never normalised."""
    if isinstance(value, bool) or not isinstance(value, (Decimal, int)):
        raise TypeError(f"{name} is a Decimal or an int, not {type(value).__name__}")
    if isinstance(value, int):
        integer, scale = value, 0
    else:
        sign, digits, exponent = value.as_tuple()
        if not isinstance(exponent, int):
            raise ValueError(f"{name} is not a finite number")
        magnitude = int("".join(map(str, digits))) * 10 ** max(exponent, 0)
        integer, scale = -magnitude if sign else magnitude, max(-exponent, 0)
    if scale > _MOST_PLACES:
        raise ValueError(
            f"{name} has {scale} decimal places; at most {_MOST_PLACES} cross the wire, "
            "and it is refused rather than rounded"
        )
    if abs(integer) >= _TOO_MANY_DIGITS:
        raise ValueError(f"{name} has more than 38 digits; it is refused rather than rounded")
    return ops.Decimal(high=integer >> 64, low=integer & _LOW_HALF, scale=scale)


def _money(value: Money, name: str) -> ops.Money:
    """An amount and its currency, the amount converted as any Decimal is."""
    if not isinstance(value, Money):
        raise TypeError(f"{name} is a meridian.Money, not {type(value).__name__}")
    if not isinstance(value.currency_code, str):
        raise TypeError(f"{name}'s currency_code is a str, not {type(value.currency_code).__name__}")
    return ops.Money(amount=_decimal(value.amount, name), currency_code=value.currency_code)


def _enum(kind: Any, value: Any, name: str) -> Any:
    """An enum value as the wire carries it: one `kind` defines, given as the
    value, its name (ASSET_CLASS_EQUITY) or its name without the enum's
    prefix in lower case (equity). None or an empty string is unset. Anything
    else is refused naming the field, never sent for the sidecar to refuse."""
    if value is None or value == "":
        return None
    prefix = re.sub(r"(?<!^)(?=[A-Z])", "_", kind.DESCRIPTOR.name).upper() + "_"
    names = dict(kind.items())
    short = {n.removeprefix(prefix).lower(): v for n, v in names.items() if n.startswith(prefix)}
    if isinstance(value, str):
        if value in names:
            return names[value]
        if value in short:
            return short[value]
    elif isinstance(value, int) and not isinstance(value, bool) and value in names.values():
        return value
    raise ValueError(
        f"{name} is {value!r}, which {kind.DESCRIPTOR.name} does not define; "
        f"one of {', '.join(n for n in short if n != 'unspecified') or ', '.join(names)}"
    )


def as_decimal(message: ops.Decimal) -> Decimal:
    """A Decimal read back from the wire exactly as it was stated: 150 at scale
    2 is Decimal('1.50'). Built from its digits rather than by arithmetic,
    which would round at the context's precision."""
    integer = (message.high << 64) | message.low
    if message.scale > _MOST_PLACES or abs(integer) >= _TOO_MANY_DIGITS:
        raise ValueError(f"{integer} at scale {message.scale} is outside what the wire carries")
    digits = tuple(int(digit) for digit in str(abs(integer)))
    return Decimal((int(integer < 0), digits, -message.scale))


def as_money(message: ops.Money) -> Money:
    """A Money read back from the wire, its amount as as_decimal reads it."""
    return Money(as_decimal(message.amount), message.currency_code)


@dataclass(frozen=True, kw_only=True)
class StatementFigures:
    """A statement's figures for one margin segment, each as the venue
    reported it and unset where it reported none; never derived.

    The SDK's form of the wire's StatementFigures: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    segment: str = ""
    buying_power: Money | None = None
    margin_requirement: Money | None = None
    maintenance_excess: Money | None = None
    initial_margin: Money | None = None
    variation_margin: Money | None = None
    net_liquidation: Money | None = None
    collateral: Sequence[ReportedCollateral] = ()


def _statement_figures(value: StatementFigures, name: str) -> ops.StatementFigures:
    """A StatementFigures as the wire carries it, or refused naming `name`."""
    if not isinstance(value, StatementFigures):
        raise TypeError(f"{name} is a meridian.StatementFigures, not {type(value).__name__}")
    return ops.StatementFigures(
        segment=value.segment,
        buying_power=None if value.buying_power is None else _money(value.buying_power, f"{name}.buying_power"),
        margin_requirement=None if value.margin_requirement is None else _money(value.margin_requirement, f"{name}.margin_requirement"),
        maintenance_excess=None if value.maintenance_excess is None else _money(value.maintenance_excess, f"{name}.maintenance_excess"),
        initial_margin=None if value.initial_margin is None else _money(value.initial_margin, f"{name}.initial_margin"),
        variation_margin=None if value.variation_margin is None else _money(value.variation_margin, f"{name}.variation_margin"),
        net_liquidation=None if value.net_liquidation is None else _money(value.net_liquidation, f"{name}.net_liquidation"),
        collateral=[_reported_collateral(each, f"{name}.collateral[{i}]") for i, each in enumerate(value.collateral)],
    )


@dataclass(frozen=True, kw_only=True)
class ReportedCollateral:
    """One collateral balance under a margin segment, each field as the
    venue reports it and unset where it does not; never derived.

    The SDK's form of the wire's ReportedCollateral: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    direction: ops.CollateralDirection | str | None = None
    instrument_id: str = ""
    unresolved_identifiers: Sequence[ops.Identifier] = ()
    quantity: Decimal | int
    value: Money | None = None
    haircut: Decimal | int | None = None
    value_after_haircut: Money | None = None
    held_at: str = ""


def _reported_collateral(value: ReportedCollateral, name: str) -> ops.ReportedCollateral:
    """A ReportedCollateral as the wire carries it, or refused naming `name`."""
    if not isinstance(value, ReportedCollateral):
        raise TypeError(f"{name} is a meridian.ReportedCollateral, not {type(value).__name__}")
    return ops.ReportedCollateral(
        direction=_enum(ops.CollateralDirection, value.direction, f"{name}.direction"),
        instrument_id=value.instrument_id,
        unresolved_identifiers=list(value.unresolved_identifiers),
        quantity=_decimal(value.quantity, f"{name}.quantity"),
        value=None if value.value is None else _money(value.value, f"{name}.value"),
        haircut=None if value.haircut is None else _decimal(value.haircut, f"{name}.haircut"),
        value_after_haircut=None if value.value_after_haircut is None else _money(value.value_after_haircut, f"{name}.value_after_haircut"),
        held_at=value.held_at,
    )


@dataclass(frozen=True, kw_only=True)
class ReportedLot:
    """One lot of a holding, as the custodian lists it.

    The SDK's form of the wire's ReportedLot: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    quantity: Decimal | int
    cost: Money | None = None
    acquired_date: str = ""


def _reported_lot(value: ReportedLot, name: str) -> ops.ReportedLot:
    """A ReportedLot as the wire carries it, or refused naming `name`."""
    if not isinstance(value, ReportedLot):
        raise TypeError(f"{name} is a meridian.ReportedLot, not {type(value).__name__}")
    return ops.ReportedLot(
        quantity=_decimal(value.quantity, f"{name}.quantity"),
        cost=None if value.cost is None else _money(value.cost, f"{name}.cost"),
        acquired_date=value.acquired_date,
    )


def _assertion(header: str | None) -> sidecar_pb2.CallerAssertion | None:
    """The person a command is sent for, from the Meridian-Caller header as the
    plugin received it: base64url, unpadded. Handed back to the sidecar, which
    verifies it; nothing here does (W4.9)."""
    if header is None:
        return None
    padded = header + "=" * (-len(header) % 4)
    return sidecar_pb2.CallerAssertion.FromString(base64.urlsafe_b64decode(padded))


class Operations:
    """Mixed into Plugin, which supplies the call."""

    async def _operate(
        self, method: Callable[[Any], Awaitable[_Answer]], params: Any
    ) -> _Answer:  # pragma: no cover - Plugin's
        raise NotImplementedError

    def _operations(self) -> Any:  # pragma: no cover - Plugin's
        raise NotImplementedError

    async def _receive(
        self, handlers: dict[str, Callable[[Any], Awaitable[None]] | None], *, seed: bool
    ) -> None:  # pragma: no cover - Plugin's
        raise NotImplementedError

    async def report_external_accounts(
        self,
        *,
        accounts: Sequence[ops.ExternalAccount] = (),
    ) -> ops.Published:
        """W2.8: Every external account a connection reaches, as the connector sees it now."""
        params = ops.ReportExternalAccountsParams(
            accounts=list(accounts),
        )
        return await self._operate(self._operations().ReportExternalAccounts, params)

    async def report_sync_status(
        self,
        *,
        source: str = "",
        last_synced_at_ns: int = 0,
        connection_healthy: bool = False,
        status_detail: str = "",
        observed_at_ns: int = 0,
        external_account_id: str = "",
        state: ops.SyncState | str | None = None,
        holdings_as_of_ns: int = 0,
        history_as_of_ns: int = 0,
    ) -> ops.Published:
        """W2.1: How fresh a connected account's data is, as reported by the rail."""
        params = ops.ReportSyncStatusParams(
            source=source,
            last_synced_at_ns=last_synced_at_ns,
            connection_healthy=connection_healthy,
            status_detail=status_detail,
            observed_at_ns=observed_at_ns,
            external_account_id=external_account_id,
            state=_enum(ops.SyncState, state, "state"),
            holdings_as_of_ns=holdings_as_of_ns,
            history_as_of_ns=history_as_of_ns,
        )
        return await self._operate(self._operations().ReportSyncStatus, params)

    async def record_holdings_statement(
        self,
        *,
        source: str = "",
        external_statement_id: str = "",
        as_of_date: str = "",
        read_at_ns: int = 0,
        expected_rows: int = 0,
        buying_power: Money | None = None,
        margin_requirement: Money | None = None,
        maintenance_excess: Money | None = None,
        currency_assumed: bool = False,
        external_account_id: str = "",
        figures: Sequence[StatementFigures] = (),
        institution: str = "",
        acting_for: str | None = None,
    ) -> ops.RecordHoldingsStatementResult:
        """W2.2: Open one statement: the connector's snapshot of one account, at one moment."""
        params = ops.RecordHoldingsStatementParams(
            source=source,
            external_statement_id=external_statement_id,
            as_of_date=as_of_date,
            read_at_ns=read_at_ns,
            expected_rows=expected_rows,
            buying_power=None if buying_power is None else _money(buying_power, "buying_power"),
            margin_requirement=None if margin_requirement is None else _money(margin_requirement, "margin_requirement"),
            maintenance_excess=None if maintenance_excess is None else _money(maintenance_excess, "maintenance_excess"),
            currency_assumed=currency_assumed,
            external_account_id=external_account_id,
            figures=[_statement_figures(each, f"figures[{i}]") for i, each in enumerate(figures)],
            institution=institution,
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().RecordHoldingsStatement, params)

    async def record_holding(
        self,
        *,
        statement_id: str = "",
        instrument_id: str = "",
        unresolved_identifiers: Sequence[ops.Identifier] = (),
        quantity: Decimal | int,
        market_value: Money | None = None,
        external_account_id: str = "",
        side: ops.HoldingSide | str | None = None,
        settle_date_quantity: Decimal | int | None = None,
        currency_assumed: bool = False,
        also_counted_in_cash: bool = False,
        cost_basis: Money | None = None,
        lots: Sequence[ReportedLot] = (),
        margin_requirement: Money | None = None,
        average_cost: Money | None = None,
        acting_for: str | None = None,
    ) -> ops.RecordHoldingResult:
        """W2.3: One holding, for one account, at one instrument, on one side."""
        params = ops.RecordHoldingParams(
            statement_id=statement_id,
            instrument_id=instrument_id,
            unresolved_identifiers=list(unresolved_identifiers),
            quantity=_decimal(quantity, "quantity"),
            market_value=None if market_value is None else _money(market_value, "market_value"),
            external_account_id=external_account_id,
            side=_enum(ops.HoldingSide, side, "side"),
            settle_date_quantity=None if settle_date_quantity is None else _decimal(settle_date_quantity, "settle_date_quantity"),
            currency_assumed=currency_assumed,
            also_counted_in_cash=also_counted_in_cash,
            cost_basis=None if cost_basis is None else _money(cost_basis, "cost_basis"),
            lots=[_reported_lot(each, f"lots[{i}]") for i, each in enumerate(lots)],
            margin_requirement=None if margin_requirement is None else _money(margin_requirement, "margin_requirement"),
            average_cost=None if average_cost is None else _money(average_cost, "average_cost"),
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().RecordHolding, params)

    async def list_custodial_positions(
        self,
        *,
        account_id: str = "",
        include_unresolved: bool = False,
        page_size: int = 0,
        cursor: str = "",
        since: ops.Watermark | None = None,
    ) -> ops.ListCustodialPositionsResult:
        """W2.7: Read custodial positions, and the unresolved holdings beside them (W2.7)."""
        params = ops.ListCustodialPositionsParams(
            account_id=account_id,
            include_unresolved=include_unresolved,
            page_size=page_size,
            cursor=cursor,
            since=since,
        )
        return await self._operate(self._operations().ListCustodialPositions, params)

    async def list_statements(
        self,
        *,
        account_id: str = "",
        as_of_date: str = "",
        since: ops.Watermark | None = None,
        page_size: int = 0,
        cursor: str = "",
    ) -> ops.ListStatementsResult:
        """W2.9: Read completed statements and their figures (W2.9)."""
        params = ops.ListStatementsParams(
            account_id=account_id,
            as_of_date=as_of_date,
            since=since,
            page_size=page_size,
            cursor=cursor,
        )
        return await self._operate(self._operations().ListStatements, params)

    async def resolve_identifier(
        self,
        *,
        identifiers: Sequence[ops.Identifier] = (),
        as_of_ns: int = 0,
        exchange_mic: str = "",
        currency: str = "",
    ) -> ops.ResolveIdentifierResult:
        """W3.1: Reverse resolution: identifiers to an instrument, as of a date."""
        params = ops.ResolveIdentifierParams(
            identifiers=list(identifiers),
            as_of_ns=as_of_ns,
            exchange_mic=exchange_mic,
            currency=currency,
        )
        return await self._operate(self._operations().ResolveIdentifier, params)

    async def report_missing_instrument(
        self,
        *,
        source: str = "",
        asset_class: ops.AssetClass | str | None = None,
        identifiers: Sequence[ops.Identifier] = (),
        as_of_ns: int = 0,
        reason: ops.MissReason | str | None = None,
        observed_at_ns: int = 0,
    ) -> ops.Published:
        """W3.2: A resolution missed. A fact, not a request."""
        params = ops.ReportMissingInstrumentParams(
            source=source,
            asset_class=_enum(ops.AssetClass, asset_class, "asset_class"),
            identifiers=list(identifiers),
            as_of_ns=as_of_ns,
            reason=_enum(ops.MissReason, reason, "reason"),
            observed_at_ns=observed_at_ns,
        )
        return await self._operate(self._operations().ReportMissingInstrument, params)

    async def link_external_account(
        self,
        *,
        external_account_id: str = "",
        account_id: str = "",
        new_account_name: str = "",
        new_account_custodian: str = "",
        new_account_type: str = "",
        new_account_owner: str = "",
        new_account_note: str = "",
        acting_for: str | None = None,
    ) -> ops.LinkExternalAccountResult:
        """W6.4: Links an external account a plugin reported, or removes its link."""
        params = ops.LinkExternalAccountParams(
            external_account_id=external_account_id,
            account_id=account_id,
            new_account_name=new_account_name,
            new_account_custodian=new_account_custodian,
            new_account_type=new_account_type,
            new_account_owner=new_account_owner,
            new_account_note=new_account_note,
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().LinkExternalAccount, params)

    async def read_accounts_for_linking(
        self,
        *,
        acting_for: str | None = None,
    ) -> ops.ReadAccountsForLinkingResult:
        """W6.4: The deployment's accounts, read by a plugin acting for its admin."""
        params = ops.ReadAccountsForLinkingParams(
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().ReadAccountsForLinking, params)

    async def receive(
        self,
        *,
        statement_recorded: Callable[[Heard[ops.StatementRecordedEvent]], Awaitable[None]] | None = None,
        custodial_position_updated: Callable[[Heard[ops.CustodialPositionUpdatedEvent]], Awaitable[None]] | None = None,
        seed: bool = True,
    ) -> None:
        """W4.3: hear the rows given a handler, each change once and in order,
        within the plugin's read scope, until cancelled. Seeded first from the
        store when `seed`; on a gap, a loss or a broken stream, caught up from
        it by each row's query, the handler told by `Heard.caught_up`. A row
        no role of the plugin hears raises NotGranted."""
        await self._receive(
            {
                "StatementRecorded": statement_recorded,
                "CustodialPositionUpdated": custodial_position_updated,
            },
            seed=seed,
        )


@dataclass(frozen=True)
class DeliveredRow:
    """A row a plugin's roles may hear (W4.3), as matrix/scoped.tsv declares
    it: the Delivery's arm carrying it, the path to the account its message
    names (empty when it names none), and the query that reads its changes
    since a watermark, given one account in `account_param`, whose reply
    holds them in `records`, each a record whose last change is in
    `record_journal` and whose account is at `record_account`; a record goes
    into the row's message at `within`, or is the row's message where that
    is empty."""

    name: str
    step: str
    arm: str
    message: Any
    account: tuple[str, ...]
    caught_up_by: str
    account_param: str
    records: str
    within: str
    record_journal: str
    record_account: tuple[str, ...]


#: Every row a plugin's roles may hear, by the arm number of its delivery.
DELIVERED: tuple[DeliveredRow, ...] = (
    DeliveredRow(
        name="StatementRecorded",
        step="W2.5",
        arm="statement_recorded",
        message=ops.StatementRecordedEvent,
        account=("account_id",),
        caught_up_by="list_statements",
        account_param="account_id",
        records="statements",
        within="",
        record_journal="journal",
        record_account=("account_id",),
    ),
    DeliveredRow(
        name="CustodialPositionUpdated",
        step="W2.6",
        arm="custodial_position_updated",
        message=ops.CustodialPositionUpdatedEvent,
        account=("position", "account_id"),
        caught_up_by="list_custodial_positions",
        account_param="account_id",
        records="positions",
        within="position",
        record_journal="last_change",
        record_account=("account_id",),
    ),
)
