"""Generated by meridian-design's tools/generate_typed_operations.py from the matrix and the domain protos (spec/typed-sidecar-operations). Do not edit.

The operations a plugin performs, one per bus row its roles may publish.

A quantity is a Python Decimal (or an int) here and a meridian.v1.Decimal on
the wire: its integer, in two 64-bit halves, and the scale it was stated
with, which is the Decimal's own exponent -- 1.50 crosses as 150 at scale 2
and reads back as 1.50. An amount of currency is a Money, a Decimal and its
ISO 4217 code. Converted once, in this file, and refused rather than
rounded: a float, more than 18 decimal places, or more than 38 digits
(decisions/023).

A plugin that reads a venue converts to the platform's convention before
it calls anything here: amounts in the currency's major unit, quantities in
the instrument's own units. It keeps what the venue sent, as sent, in its
own logs. A float the venue sent becomes Decimal(repr(value)), its shortest
round-trip form, and never Decimal(value), its binary expansion.
"""

from __future__ import annotations

import base64
import re
from collections.abc import Awaitable, Callable, Sequence
from dataclasses import dataclass
from decimal import Decimal
from typing import TYPE_CHECKING, Any, TypeVar

from meridian.plugin.v1 import operations_pb2 as ops
from meridian.v1 import sidecar_pb2

from .bounds import DECIMAL_DIGITS, DECIMAL_SCALE

if TYPE_CHECKING:
    from .receive import Heard

_Answer = TypeVar("_Answer")

# What the wire carries (decisions/023), as the data dictionary's entries
# state it (meridian.bounds): a scale of 0 to DECIMAL_SCALE.most, and an
# integer whose magnitude is below 10 to the DECIMAL_DIGITS.
_TOO_MANY_DIGITS = 10**DECIMAL_DIGITS
_LOW_HALF = 2**64 - 1


@dataclass(frozen=True)
class Money:
    """An amount of currency: a Decimal (or an int) and its ISO 4217 code.

    One value rather than an amount with its currency beside it, so a call
    carrying amounts in two currencies cannot pair either with the wrong one.
    """

    amount: Decimal | int
    currency_code: str


def _decimal(value: Decimal | int, name: str) -> ops.Decimal:
    """A number as the wire carries it: its integer, in two 64-bit halves, and
    the scale it was stated with. Exact, or refused naming the field; never
    rounded, and never normalised."""
    if isinstance(value, bool) or not isinstance(value, (Decimal, int)):
        raise TypeError(f"{name} is a Decimal or an int, not {type(value).__name__}")
    if isinstance(value, int):
        integer, scale = value, 0
    else:
        sign, digits, exponent = value.as_tuple()
        if not isinstance(exponent, int):
            raise ValueError(f"{name} is not a finite number")
        magnitude = int("".join(map(str, digits))) * 10 ** max(exponent, 0)
        integer, scale = -magnitude if sign else magnitude, max(-exponent, 0)
    if scale > DECIMAL_SCALE.most:
        raise ValueError(
            f"{name} has {scale} decimal places; at most {DECIMAL_SCALE.most} cross the wire, "
            "and it is refused rather than rounded"
        )
    if abs(integer) >= _TOO_MANY_DIGITS:
        raise ValueError(f"{name} has more than {DECIMAL_DIGITS} digits; it is refused rather than rounded")
    return ops.Decimal(high=integer >> 64, low=integer & _LOW_HALF, scale=scale)


def _money(value: Money, name: str) -> ops.Money:
    """An amount and its currency, the amount converted as any Decimal is."""
    if not isinstance(value, Money):
        raise TypeError(f"{name} is a meridian.Money, not {type(value).__name__}")
    if not isinstance(value.currency_code, str):
        raise TypeError(f"{name}'s currency_code is a str, not {type(value.currency_code).__name__}")
    return ops.Money(amount=_decimal(value.amount, name), currency_code=value.currency_code)


def _enum(kind: Any, value: Any, name: str) -> Any:
    """An enum value as the wire carries it: one `kind` defines, given as the
    value, its name (ASSET_CLASS_EQUITY) or its name without the enum's
    prefix in lower case (equity). None or an empty string is unset. Anything
    else is refused naming the field, never sent for the sidecar to refuse."""
    if value is None or value == "":
        return None
    prefix = re.sub(r"(?<!^)(?=[A-Z])", "_", kind.DESCRIPTOR.name).upper() + "_"
    names = dict(kind.items())
    short = {n.removeprefix(prefix).lower(): v for n, v in names.items() if n.startswith(prefix)}
    if isinstance(value, str):
        if value in names:
            return names[value]
        if value in short:
            return short[value]
    elif isinstance(value, int) and not isinstance(value, bool) and value in names.values():
        return value
    raise ValueError(
        f"{name} is {value!r}, which {kind.DESCRIPTOR.name} does not define; "
        f"one of {', '.join(n for n in short if n != 'unspecified') or ', '.join(names)}"
    )


def _stated(**flags: bool | None) -> dict[str, Any]:
    """An optional flag as keyword arguments for the wire's message: absent
    when None, which is "not stated" and never False (contract v8)."""
    return {name: value for name, value in flags.items() if value is not None}


def _arm(oneof: str, **arms: Any) -> dict[str, Any]:
    """The arm of a oneof that is set, as keyword arguments for the wire's
    message: none when none is, and refused naming the oneof when two are.
    Each arm is None when unset (contract v8)."""
    given = {name: value for name, value in arms.items() if value is not None}
    if len(given) > 1:
        raise ValueError(
            f"{oneof} takes one of {', '.join(arms)}; "
            f"{' and '.join(given)} were given"
        )
    return given


def as_decimal(message: ops.Decimal) -> Decimal:
    """A Decimal read back from the wire exactly as it was stated: 150 at scale
    2 is Decimal('1.50'). Built from its digits rather than by arithmetic,
    which would round at the context's precision."""
    integer = (message.high << 64) | message.low
    if message.scale > DECIMAL_SCALE.most or abs(integer) >= _TOO_MANY_DIGITS:
        raise ValueError(f"{integer} at scale {message.scale} is outside what the wire carries")
    digits = tuple(int(digit) for digit in str(abs(integer)))
    return Decimal((int(integer < 0), digits, -message.scale))


def as_money(message: ops.Money) -> Money:
    """A Money read back from the wire, its amount as as_decimal reads it."""
    return Money(as_decimal(message.amount), message.currency_code)


@dataclass(frozen=True, kw_only=True)
class ExternalAccount:
    """One account a connection reaches, as the custodian presents it.

    The SDK's form of the wire's ExternalAccount: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    external_account_id: str = ""
    name: str = ""
    venue_account_type: str = ""
    account_kind: ops.AccountKind | str | None = None
    account_kind_as_reported: ops.AsReported | None = None


def _external_account(value: ExternalAccount, name: str) -> ops.ExternalAccount:
    """A ExternalAccount as the wire carries it, or refused naming `name`."""
    if not isinstance(value, ExternalAccount):
        raise TypeError(f"{name} is a meridian.ExternalAccount, not {type(value).__name__}")
    return ops.ExternalAccount(
        external_account_id=value.external_account_id,
        name=value.name,
        venue_account_type=value.venue_account_type,
        account_kind=_enum(ops.AccountKind, value.account_kind, f"{name}.account_kind"),
        account_kind_as_reported=value.account_kind_as_reported,
    )


@dataclass(frozen=True, kw_only=True)
class StatementFigures:
    """A statement's figures for one margin segment, each as the venue
    reported it and unset where it reported none; never derived.

    The SDK's form of the wire's StatementFigures: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    segment: str = ""
    buying_power: Money | None = None
    margin_requirement: Money | None = None
    maintenance_excess: Money | None = None
    initial_margin: Money | None = None
    variation_margin: Money | None = None
    net_liquidation: Money | None = None
    collateral: Sequence[ReportedCollateral] = ()


def _statement_figures(value: StatementFigures, name: str) -> ops.StatementFigures:
    """A StatementFigures as the wire carries it, or refused naming `name`."""
    if not isinstance(value, StatementFigures):
        raise TypeError(f"{name} is a meridian.StatementFigures, not {type(value).__name__}")
    return ops.StatementFigures(
        segment=value.segment,
        buying_power=None if value.buying_power is None else _money(value.buying_power, f"{name}.buying_power"),
        margin_requirement=None if value.margin_requirement is None else _money(value.margin_requirement, f"{name}.margin_requirement"),
        maintenance_excess=None if value.maintenance_excess is None else _money(value.maintenance_excess, f"{name}.maintenance_excess"),
        initial_margin=None if value.initial_margin is None else _money(value.initial_margin, f"{name}.initial_margin"),
        variation_margin=None if value.variation_margin is None else _money(value.variation_margin, f"{name}.variation_margin"),
        net_liquidation=None if value.net_liquidation is None else _money(value.net_liquidation, f"{name}.net_liquidation"),
        collateral=[_reported_collateral(each, f"{name}.collateral[{i}]") for i, each in enumerate(value.collateral)],
    )


@dataclass(frozen=True, kw_only=True)
class ReportedCollateral:
    """One collateral balance under a margin segment, each field as the
    venue reports it and unset where it does not; never derived.

    The SDK's form of the wire's ReportedCollateral: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    direction: ops.CollateralDirection | str | None = None
    instrument_id: str = ""
    unresolved_identifiers: Sequence[ops.Identifier] = ()
    quantity: Decimal | int
    value: Money | None = None
    haircut: Decimal | int | None = None
    value_after_haircut: Money | None = None
    held_at: str = ""
    reusable: bool | None = None


def _reported_collateral(value: ReportedCollateral, name: str) -> ops.ReportedCollateral:
    """A ReportedCollateral as the wire carries it, or refused naming `name`."""
    if not isinstance(value, ReportedCollateral):
        raise TypeError(f"{name} is a meridian.ReportedCollateral, not {type(value).__name__}")
    return ops.ReportedCollateral(
        direction=_enum(ops.CollateralDirection, value.direction, f"{name}.direction"),
        instrument_id=value.instrument_id,
        unresolved_identifiers=list(value.unresolved_identifiers),
        quantity=_decimal(value.quantity, f"{name}.quantity"),
        value=None if value.value is None else _money(value.value, f"{name}.value"),
        haircut=None if value.haircut is None else _decimal(value.haircut, f"{name}.haircut"),
        value_after_haircut=None if value.value_after_haircut is None else _money(value.value_after_haircut, f"{name}.value_after_haircut"),
        held_at=value.held_at,
        **_stated(reusable=value.reusable),
    )


@dataclass(frozen=True, kw_only=True)
class Provenance:
    """Where a value a plugin sent came from, where the plugin closed it
    rather than read it from its vendor (requirements 31 to 34; plans/an-
    order-reaches- a-venue-through-the-book, Q13).

    The SDK's form of the wire's Provenance: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    field: str = ""
    kind: ops.ProvenanceKind | str | None = None
    raw_record: ops.RawRecordRef | None = None
    source: str = ""
    person: str = ""
    rule: str = ""


def _provenance(value: Provenance, name: str) -> ops.Provenance:
    """A Provenance as the wire carries it, or refused naming `name`."""
    if not isinstance(value, Provenance):
        raise TypeError(f"{name} is a meridian.Provenance, not {type(value).__name__}")
    return ops.Provenance(
        field=value.field,
        kind=_enum(ops.ProvenanceKind, value.kind, f"{name}.kind"),
        raw_record=value.raw_record,
        source=value.source,
        person=value.person,
        rule=value.rule,
    )


@dataclass(frozen=True, kw_only=True)
class ReportedLot:
    """One lot of a holding, as the custodian lists it.

    The SDK's form of the wire's ReportedLot: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    quantity: Decimal | int
    cost: Money | None = None
    acquired_date: str = ""


def _reported_lot(value: ReportedLot, name: str) -> ops.ReportedLot:
    """A ReportedLot as the wire carries it, or refused naming `name`."""
    if not isinstance(value, ReportedLot):
        raise TypeError(f"{name} is a meridian.ReportedLot, not {type(value).__name__}")
    return ops.ReportedLot(
        quantity=_decimal(value.quantity, f"{name}.quantity"),
        cost=None if value.cost is None else _money(value.cost, f"{name}.cost"),
        acquired_date=value.acquired_date,
    )


@dataclass(frozen=True, kw_only=True)
class ReportedEncumbrance:
    """One sub-balance of a holding, as the source reports it.

    The SDK's form of the wire's ReportedEncumbrance: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    kind: ops.EncumbranceKind | str | None = None
    quantity: Decimal | int
    available: bool | None = None
    source_code: str = ""
    pledgee: str = ""
    held_at: str = ""
    segment: str = ""
    detail: str = ""


def _reported_encumbrance(value: ReportedEncumbrance, name: str) -> ops.ReportedEncumbrance:
    """A ReportedEncumbrance as the wire carries it, or refused naming `name`."""
    if not isinstance(value, ReportedEncumbrance):
        raise TypeError(f"{name} is a meridian.ReportedEncumbrance, not {type(value).__name__}")
    return ops.ReportedEncumbrance(
        kind=_enum(ops.EncumbranceKind, value.kind, f"{name}.kind"),
        quantity=_decimal(value.quantity, f"{name}.quantity"),
        **_stated(available=value.available),
        source_code=value.source_code,
        pledgee=value.pledgee,
        held_at=value.held_at,
        segment=value.segment,
        detail=value.detail,
    )


@dataclass(frozen=True, kw_only=True)
class ReportedPending:
    """A quantity not yet settled, and the date it is due to (W2.3, contract
    v11).

    The SDK's form of the wire's ReportedPending: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    value_date: str = ""
    quantity: Decimal | int


def _reported_pending(value: ReportedPending, name: str) -> ops.ReportedPending:
    """A ReportedPending as the wire carries it, or refused naming `name`."""
    if not isinstance(value, ReportedPending):
        raise TypeError(f"{name} is a meridian.ReportedPending, not {type(value).__name__}")
    return ops.ReportedPending(
        value_date=value.value_date,
        quantity=_decimal(value.quantity, f"{name}.quantity"),
    )


@dataclass(frozen=True, kw_only=True)
class CustodialActivity:
    """One activity on an account, as the custodian states it: a purchase, a
    sale, a reinvested dividend, a dividend or interest, a fee or a tax, a
    split or another corporate action, a transfer, a contribution, a
    withdrawal or a journal (spec/the-custodians-activity-explains-a-break).

    The SDK's form of the wire's CustodialActivity: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    external_activity_id: str = ""
    kind: ops.ActivityKind | str | None = None
    kind_as_reported: ops.AsReported | None = None
    instrument_id: str = ""
    instrument_as_reported: ops.AsReported | None = None
    trade_date: str = ""
    settlement_date: str = ""
    units: Decimal | int | None = None
    price: Money | None = None
    amount: Money | None = None
    description: str = ""
    raw_record: ops.RawRecordRef | None = None
    provenance: Sequence[Provenance] = ()


def _custodial_activity(value: CustodialActivity, name: str) -> ops.CustodialActivity:
    """A CustodialActivity as the wire carries it, or refused naming `name`."""
    if not isinstance(value, CustodialActivity):
        raise TypeError(f"{name} is a meridian.CustodialActivity, not {type(value).__name__}")
    return ops.CustodialActivity(
        external_activity_id=value.external_activity_id,
        kind=_enum(ops.ActivityKind, value.kind, f"{name}.kind"),
        kind_as_reported=value.kind_as_reported,
        instrument_id=value.instrument_id,
        instrument_as_reported=value.instrument_as_reported,
        trade_date=value.trade_date,
        settlement_date=value.settlement_date,
        units=None if value.units is None else _decimal(value.units, f"{name}.units"),
        price=None if value.price is None else _money(value.price, f"{name}.price"),
        amount=None if value.amount is None else _money(value.amount, f"{name}.amount"),
        description=value.description,
        raw_record=value.raw_record,
        provenance=[_provenance(each, f"{name}.provenance[{i}]") for i, each in enumerate(value.provenance)],
    )


@dataclass(frozen=True, kw_only=True)
class OpeningSource:
    """OpeningSource.

    The SDK's form of the wire's OpeningSource: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    kind: ops.OpeningSourceKind | str | None = None
    name: str = ""
    as_of_date: str = ""
    basis: ops.PositionBasis | str | None = None
    street_records: Sequence[ops.StreetRecordRef] = ()


def _opening_source(value: OpeningSource, name: str) -> ops.OpeningSource:
    """A OpeningSource as the wire carries it, or refused naming `name`."""
    if not isinstance(value, OpeningSource):
        raise TypeError(f"{name} is a meridian.OpeningSource, not {type(value).__name__}")
    return ops.OpeningSource(
        kind=_enum(ops.OpeningSourceKind, value.kind, f"{name}.kind"),
        name=value.name,
        as_of_date=value.as_of_date,
        basis=_enum(ops.PositionBasis, value.basis, f"{name}.basis"),
        street_records=list(value.street_records),
    )


@dataclass(frozen=True, kw_only=True)
class OpeningPosition:
    """OpeningPosition.

    The SDK's form of the wire's OpeningPosition: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    instrument_id: str = ""
    side: ops.HoldingSide | str | None = None
    trade_date_quantity: Decimal | int
    settled_quantity: Decimal | int | None = None
    pending: Sequence[PendingSettlement] = ()
    lots: Sequence[OpeningLot] = ()


def _opening_position(value: OpeningPosition, name: str) -> ops.OpeningPosition:
    """A OpeningPosition as the wire carries it, or refused naming `name`."""
    if not isinstance(value, OpeningPosition):
        raise TypeError(f"{name} is a meridian.OpeningPosition, not {type(value).__name__}")
    return ops.OpeningPosition(
        instrument_id=value.instrument_id,
        side=_enum(ops.HoldingSide, value.side, f"{name}.side"),
        trade_date_quantity=_decimal(value.trade_date_quantity, f"{name}.trade_date_quantity"),
        settled_quantity=None if value.settled_quantity is None else _decimal(value.settled_quantity, f"{name}.settled_quantity"),
        pending=[_pending_settlement(each, f"{name}.pending[{i}]") for i, each in enumerate(value.pending)],
        lots=[_opening_lot(each, f"{name}.lots[{i}]") for i, each in enumerate(value.lots)],
    )


@dataclass(frozen=True, kw_only=True)
class PendingSettlement:
    """PendingSettlement.

    The SDK's form of the wire's PendingSettlement: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    value_date: str = ""
    quantity: Decimal | int
    state: ops.PendingState | None = None


def _pending_settlement(value: PendingSettlement, name: str) -> ops.PendingSettlement:
    """A PendingSettlement as the wire carries it, or refused naming `name`."""
    if not isinstance(value, PendingSettlement):
        raise TypeError(f"{name} is a meridian.PendingSettlement, not {type(value).__name__}")
    return ops.PendingSettlement(
        value_date=value.value_date,
        quantity=_decimal(value.quantity, f"{name}.quantity"),
        state=value.state,
    )


@dataclass(frozen=True, kw_only=True)
class OpeningLot:
    """OpeningLot.

    The SDK's form of the wire's OpeningLot: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    quantity: Decimal | int
    terms: LotTerms | None = None


def _opening_lot(value: OpeningLot, name: str) -> ops.OpeningLot:
    """A OpeningLot as the wire carries it, or refused naming `name`."""
    if not isinstance(value, OpeningLot):
        raise TypeError(f"{name} is a meridian.OpeningLot, not {type(value).__name__}")
    return ops.OpeningLot(
        quantity=_decimal(value.quantity, f"{name}.quantity"),
        terms=None if value.terms is None else _lot_terms(value.terms, f"{name}.terms"),
    )


@dataclass(frozen=True, kw_only=True)
class LotTerms:
    """LotTerms.

    The SDK's form of the wire's LotTerms: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    unit_cost: Money | None = None
    cost: Money | None = None
    acquired_date: str = ""
    holding_period_start: str = ""
    settlement_date: str = ""
    source: ops.LotSource | str | None = None


def _lot_terms(value: LotTerms, name: str) -> ops.LotTerms:
    """A LotTerms as the wire carries it, or refused naming `name`."""
    if not isinstance(value, LotTerms):
        raise TypeError(f"{name} is a meridian.LotTerms, not {type(value).__name__}")
    return ops.LotTerms(
        unit_cost=None if value.unit_cost is None else _money(value.unit_cost, f"{name}.unit_cost"),
        cost=None if value.cost is None else _money(value.cost, f"{name}.cost"),
        acquired_date=value.acquired_date,
        holding_period_start=value.holding_period_start,
        settlement_date=value.settlement_date,
        source=_enum(ops.LotSource, value.source, f"{name}.source"),
    )


@dataclass(frozen=True, kw_only=True)
class PositionKey:
    """PositionKey.

    The SDK's form of the wire's PositionKey: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    instrument_id: str = ""
    side: ops.HoldingSide | str | None = None


def _position_key(value: PositionKey, name: str) -> ops.PositionKey:
    """A PositionKey as the wire carries it, or refused naming `name`."""
    if not isinstance(value, PositionKey):
        raise TypeError(f"{name} is a meridian.PositionKey, not {type(value).__name__}")
    return ops.PositionKey(
        instrument_id=value.instrument_id,
        side=_enum(ops.HoldingSide, value.side, f"{name}.side"),
    )


@dataclass(frozen=True, kw_only=True)
class BreakDifference:
    """BreakDifference.

    The SDK's form of the wire's BreakDifference: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    field: str = ""
    book: BreakValue | None = None
    street: BreakValue | None = None


def _break_difference(value: BreakDifference, name: str) -> ops.BreakDifference:
    """A BreakDifference as the wire carries it, or refused naming `name`."""
    if not isinstance(value, BreakDifference):
        raise TypeError(f"{name} is a meridian.BreakDifference, not {type(value).__name__}")
    return ops.BreakDifference(
        field=value.field,
        book=None if value.book is None else _break_value(value.book, f"{name}.book"),
        street=None if value.street is None else _break_value(value.street, f"{name}.street"),
    )


@dataclass(frozen=True, kw_only=True)
class BreakValue:
    """One side of a difference; unset: absent on that side.

    The SDK's form of the wire's BreakValue: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    quantity: Decimal | int | None = None
    amount: Money | None = None
    text: str | None = None


def _break_value(value: BreakValue, name: str) -> ops.BreakValue:
    """A BreakValue as the wire carries it, or refused naming `name`."""
    if not isinstance(value, BreakValue):
        raise TypeError(f"{name} is a meridian.BreakValue, not {type(value).__name__}")
    return ops.BreakValue(
        **_arm(f"{name}.value", quantity=None if value.quantity is None else _decimal(value.quantity, f"{name}.quantity"), amount=None if value.amount is None else _money(value.amount, f"{name}.amount"), text=value.text),
    )


@dataclass(frozen=True, kw_only=True)
class BreakCause:
    """The item found to cause a break, linked by value (Q23's target).

    The SDK's form of the wire's BreakCause: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    category: ops.BreakCauseCategory | str | None = None
    street_record: ops.StreetRecordRef | None = None
    book_entry: ops.JournalRef | None = None
    pending_settlement: PendingSettlementRef | None = None
    event_reference: str | None = None
    none_found: bool | None = None
    activity: ops.ActivityRef | None = None
    note: str = ""


def _break_cause(value: BreakCause, name: str) -> ops.BreakCause:
    """A BreakCause as the wire carries it, or refused naming `name`."""
    if not isinstance(value, BreakCause):
        raise TypeError(f"{name} is a meridian.BreakCause, not {type(value).__name__}")
    return ops.BreakCause(
        category=_enum(ops.BreakCauseCategory, value.category, f"{name}.category"),
        **_arm(f"{name}.item", street_record=value.street_record, book_entry=value.book_entry, pending_settlement=None if value.pending_settlement is None else _pending_settlement_ref(value.pending_settlement, f"{name}.pending_settlement"), event_reference=value.event_reference, none_found=value.none_found, activity=value.activity),
        note=value.note,
    )


@dataclass(frozen=True, kw_only=True)
class PendingSettlementRef:
    """PendingSettlementRef.

    The SDK's form of the wire's PendingSettlementRef: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    instrument_id: str = ""
    side: ops.HoldingSide | str | None = None
    value_date: str = ""


def _pending_settlement_ref(value: PendingSettlementRef, name: str) -> ops.PendingSettlementRef:
    """A PendingSettlementRef as the wire carries it, or refused naming `name`."""
    if not isinstance(value, PendingSettlementRef):
        raise TypeError(f"{name} is a meridian.PendingSettlementRef, not {type(value).__name__}")
    return ops.PendingSettlementRef(
        instrument_id=value.instrument_id,
        side=_enum(ops.HoldingSide, value.side, f"{name}.side"),
        value_date=value.value_date,
    )


@dataclass(frozen=True, kw_only=True)
class AgreementFigures:
    """AgreementFigures.

    The SDK's form of the wire's AgreementFigures: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    agreement: ops.MarginAgreementRef | None = None
    figures: StatementFigures | None = None
    position_values: Sequence[ReportedPositionValue] = ()


def _agreement_figures(value: AgreementFigures, name: str) -> ops.AgreementFigures:
    """A AgreementFigures as the wire carries it, or refused naming `name`."""
    if not isinstance(value, AgreementFigures):
        raise TypeError(f"{name} is a meridian.AgreementFigures, not {type(value).__name__}")
    return ops.AgreementFigures(
        agreement=value.agreement,
        figures=None if value.figures is None else _statement_figures(value.figures, f"{name}.figures"),
        position_values=[_reported_position_value(each, f"{name}.position_values[{i}]") for i, each in enumerate(value.position_values)],
    )


@dataclass(frozen=True, kw_only=True)
class ReportedPositionValue:
    """The custodian's, labelled as such (Q8, revised and ruled); never a
    position's own.

    The SDK's form of the wire's ReportedPositionValue: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    instrument_id: str = ""
    side: ops.HoldingSide | str | None = None
    market_value: Money | None = None
    margin_requirement: Money | None = None


def _reported_position_value(value: ReportedPositionValue, name: str) -> ops.ReportedPositionValue:
    """A ReportedPositionValue as the wire carries it, or refused naming `name`."""
    if not isinstance(value, ReportedPositionValue):
        raise TypeError(f"{name} is a meridian.ReportedPositionValue, not {type(value).__name__}")
    return ops.ReportedPositionValue(
        instrument_id=value.instrument_id,
        side=_enum(ops.HoldingSide, value.side, f"{name}.side"),
        market_value=None if value.market_value is None else _money(value.market_value, f"{name}.market_value"),
        margin_requirement=None if value.margin_requirement is None else _money(value.margin_requirement, f"{name}.margin_requirement"),
    )


@dataclass(frozen=True, kw_only=True)
class PositionEncumbrances:
    """One position's encumbrances, as a statement states them: the whole
    set, empty when the statement reports none.

    The SDK's form of the wire's PositionEncumbrances: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    instrument_id: str = ""
    side: ops.HoldingSide | str | None = None
    encumbrances: Sequence[Encumbrance] = ()


def _position_encumbrances(value: PositionEncumbrances, name: str) -> ops.PositionEncumbrances:
    """A PositionEncumbrances as the wire carries it, or refused naming `name`."""
    if not isinstance(value, PositionEncumbrances):
        raise TypeError(f"{name} is a meridian.PositionEncumbrances, not {type(value).__name__}")
    return ops.PositionEncumbrances(
        instrument_id=value.instrument_id,
        side=_enum(ops.HoldingSide, value.side, f"{name}.side"),
        encumbrances=[_encumbrance(each, f"{name}.encumbrances[{i}]") for i, each in enumerate(value.encumbrances)],
    )


@dataclass(frozen=True, kw_only=True)
class Encumbrance:
    """One encumbrance of a position, as the book holds it.

    The SDK's form of the wire's Encumbrance: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    kind: ops.EncumbranceKind | str | None = None
    quantity: Decimal | int
    pledgee: str = ""
    held_at: str = ""
    agreement: ops.MarginAgreementRef | None = None
    source_code: str = ""
    detail: str = ""
    source: ops.StreetRecordRef | None = None
    since_date: str = ""
    set_by: ops.JournalRef | None = None


def _encumbrance(value: Encumbrance, name: str) -> ops.Encumbrance:
    """A Encumbrance as the wire carries it, or refused naming `name`."""
    if not isinstance(value, Encumbrance):
        raise TypeError(f"{name} is a meridian.Encumbrance, not {type(value).__name__}")
    return ops.Encumbrance(
        kind=_enum(ops.EncumbranceKind, value.kind, f"{name}.kind"),
        quantity=_decimal(value.quantity, f"{name}.quantity"),
        pledgee=value.pledgee,
        held_at=value.held_at,
        agreement=value.agreement,
        source_code=value.source_code,
        detail=value.detail,
        source=value.source,
        since_date=value.since_date,
        set_by=value.set_by,
    )


@dataclass(frozen=True, kw_only=True)
class Adjustment:
    """Step 5's non-order transaction's first kind (Q28).

    The SDK's form of the wire's Adjustment: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    effective_date: str = ""
    lines: Sequence[MovementLine] = ()
    basis_adjustments: Sequence[BasisAdjustment] = ()
    event_reference: str = ""


def _adjustment(value: Adjustment, name: str) -> ops.Adjustment:
    """A Adjustment as the wire carries it, or refused naming `name`."""
    if not isinstance(value, Adjustment):
        raise TypeError(f"{name} is a meridian.Adjustment, not {type(value).__name__}")
    return ops.Adjustment(
        effective_date=value.effective_date,
        lines=[_movement_line(each, f"{name}.lines[{i}]") for i, each in enumerate(value.lines)],
        basis_adjustments=[_basis_adjustment(each, f"{name}.basis_adjustments[{i}]") for i, each in enumerate(value.basis_adjustments)],
        event_reference=value.event_reference,
    )


@dataclass(frozen=True, kw_only=True)
class MovementLine:
    """MovementLine.

    The SDK's form of the wire's MovementLine: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    instrument_id: str = ""
    side: ops.HoldingSide | str | None = None
    bucket: ops.SettlementBucket | str | None = None
    value_date: str = ""
    quantity: Decimal | int
    lot_id: str = ""
    opens_lot: LotTerms | None = None
    pending_state: ops.PendingState | None = None


def _movement_line(value: MovementLine, name: str) -> ops.MovementLine:
    """A MovementLine as the wire carries it, or refused naming `name`."""
    if not isinstance(value, MovementLine):
        raise TypeError(f"{name} is a meridian.MovementLine, not {type(value).__name__}")
    return ops.MovementLine(
        instrument_id=value.instrument_id,
        side=_enum(ops.HoldingSide, value.side, f"{name}.side"),
        bucket=_enum(ops.SettlementBucket, value.bucket, f"{name}.bucket"),
        value_date=value.value_date,
        quantity=_decimal(value.quantity, f"{name}.quantity"),
        lot_id=value.lot_id,
        opens_lot=None if value.opens_lot is None else _lot_terms(value.opens_lot, f"{name}.opens_lot"),
        pending_state=value.pending_state,
    )


@dataclass(frozen=True, kw_only=True)
class BasisAdjustment:
    """BasisAdjustment.

    The SDK's form of the wire's BasisAdjustment: a number as a Decimal, an amount
    as a Money, an enum as its value or name, each converted and refused
    naming its path, as a request's own field is."""

    lot_id: str = ""
    cost_change: Money | None = None
    stated_cost: Money | None = None
    holding_period_start: str = ""


def _basis_adjustment(value: BasisAdjustment, name: str) -> ops.BasisAdjustment:
    """A BasisAdjustment as the wire carries it, or refused naming `name`."""
    if not isinstance(value, BasisAdjustment):
        raise TypeError(f"{name} is a meridian.BasisAdjustment, not {type(value).__name__}")
    return ops.BasisAdjustment(
        lot_id=value.lot_id,
        **_arm(f"{name}.cost", cost_change=None if value.cost_change is None else _money(value.cost_change, f"{name}.cost_change"), stated_cost=None if value.stated_cost is None else _money(value.stated_cost, f"{name}.stated_cost")),
        holding_period_start=value.holding_period_start,
    )


def _assertion(header: str | None) -> sidecar_pb2.CallerAssertion | None:
    """The person a command is sent for, from the Meridian-Caller header as the
    plugin received it: base64url, unpadded. Handed back to the sidecar, which
    verifies it; nothing here does (W4.9)."""
    if header is None:
        return None
    padded = header + "=" * (-len(header) % 4)
    return sidecar_pb2.CallerAssertion.FromString(base64.urlsafe_b64decode(padded))


class Operations:
    """Mixed into Plugin, which supplies the call."""

    async def _operate(
        self, method: Callable[[Any], Awaitable[_Answer]], params: Any
    ) -> _Answer:  # pragma: no cover - Plugin's
        raise NotImplementedError

    def _operations(self) -> Any:  # pragma: no cover - Plugin's
        raise NotImplementedError

    async def _receive(
        self, handlers: dict[str, Callable[[Any], Awaitable[None]] | None], *, seed: bool
    ) -> None:  # pragma: no cover - Plugin's
        raise NotImplementedError

    async def report_external_accounts(
        self,
        *,
        accounts: Sequence[ExternalAccount] = (),
    ) -> ops.Published:
        """W2.8: Every external account a connection reaches, as the connector sees it now (stable)."""
        params = ops.ReportExternalAccountsParams(
            accounts=[_external_account(each, f"accounts[{i}]") for i, each in enumerate(accounts)],
        )
        return await self._operate(self._operations().ReportExternalAccounts, params)

    async def report_sync_status(
        self,
        *,
        source: str = "",
        last_synced_at_ns: int = 0,
        connection_healthy: bool = False,
        status_detail: str = "",
        observed_at_ns: int = 0,
        external_account_id: str = "",
        state: ops.SyncState | str | None = None,
        holdings_as_of_ns: int = 0,
        history_as_of_ns: int = 0,
        history_from: str = "",
    ) -> ops.Published:
        """W2.1: How fresh a connected account's data is, as reported by the rail (stable)."""
        params = ops.ReportSyncStatusParams(
            source=source,
            last_synced_at_ns=last_synced_at_ns,
            connection_healthy=connection_healthy,
            status_detail=status_detail,
            observed_at_ns=observed_at_ns,
            external_account_id=external_account_id,
            state=_enum(ops.SyncState, state, "state"),
            holdings_as_of_ns=holdings_as_of_ns,
            history_as_of_ns=history_as_of_ns,
            history_from=history_from,
        )
        return await self._operate(self._operations().ReportSyncStatus, params)

    async def record_holdings_statement(
        self,
        *,
        source: str = "",
        external_statement_id: str = "",
        as_of_date: str = "",
        read_at_ns: int = 0,
        expected_rows: int = 0,
        buying_power: Money | None = None,
        margin_requirement: Money | None = None,
        maintenance_excess: Money | None = None,
        currency_assumed: bool = False,
        external_account_id: str = "",
        figures: Sequence[StatementFigures] = (),
        institution: str = "",
        security_interest: bool | None = None,
        raw_record: ops.RawRecordRef | None = None,
        provenance: Sequence[Provenance] = (),
        acting_for: str | None = None,
    ) -> ops.RecordHoldingsStatementResult:
        """W2.2: Open one statement: the connector's snapshot of one account, at one moment (stable)."""
        params = ops.RecordHoldingsStatementParams(
            source=source,
            external_statement_id=external_statement_id,
            as_of_date=as_of_date,
            read_at_ns=read_at_ns,
            expected_rows=expected_rows,
            buying_power=None if buying_power is None else _money(buying_power, "buying_power"),
            margin_requirement=None if margin_requirement is None else _money(margin_requirement, "margin_requirement"),
            maintenance_excess=None if maintenance_excess is None else _money(maintenance_excess, "maintenance_excess"),
            currency_assumed=currency_assumed,
            external_account_id=external_account_id,
            figures=[_statement_figures(each, f"figures[{i}]") for i, each in enumerate(figures)],
            institution=institution,
            **_stated(security_interest=security_interest),
            raw_record=raw_record,
            provenance=[_provenance(each, f"provenance[{i}]") for i, each in enumerate(provenance)],
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().RecordHoldingsStatement, params)

    async def record_holding(
        self,
        *,
        statement_id: str = "",
        instrument_id: str = "",
        unresolved_identifiers: Sequence[ops.Identifier] = (),
        quantity: Decimal | int,
        market_value: Money | None = None,
        external_account_id: str = "",
        side: ops.HoldingSide | str | None = None,
        settle_date_quantity: Decimal | int | None = None,
        currency_assumed: bool = False,
        also_counted_in_cash: bool = False,
        cost_basis: Money | None = None,
        lots: Sequence[ReportedLot] = (),
        margin_requirement: Money | None = None,
        average_cost: Money | None = None,
        available_quantity: Decimal | int | None = None,
        not_available_quantity: Decimal | int | None = None,
        available_basis: ops.AvailableBasis | str | None = None,
        encumbrances: Sequence[ReportedEncumbrance] = (),
        raw_record: ops.RawRecordRef | None = None,
        provenance: Sequence[Provenance] = (),
        pending: Sequence[ReportedPending] = (),
        backfill: ops.Backfill | None = None,
        acting_for: str | None = None,
    ) -> ops.RecordHoldingResult:
        """W2.3: One holding, for one account, at one instrument, on one side (stable)."""
        params = ops.RecordHoldingParams(
            statement_id=statement_id,
            instrument_id=instrument_id,
            unresolved_identifiers=list(unresolved_identifiers),
            quantity=_decimal(quantity, "quantity"),
            market_value=None if market_value is None else _money(market_value, "market_value"),
            external_account_id=external_account_id,
            side=_enum(ops.HoldingSide, side, "side"),
            settle_date_quantity=None if settle_date_quantity is None else _decimal(settle_date_quantity, "settle_date_quantity"),
            currency_assumed=currency_assumed,
            also_counted_in_cash=also_counted_in_cash,
            cost_basis=None if cost_basis is None else _money(cost_basis, "cost_basis"),
            lots=[_reported_lot(each, f"lots[{i}]") for i, each in enumerate(lots)],
            margin_requirement=None if margin_requirement is None else _money(margin_requirement, "margin_requirement"),
            average_cost=None if average_cost is None else _money(average_cost, "average_cost"),
            available_quantity=None if available_quantity is None else _decimal(available_quantity, "available_quantity"),
            not_available_quantity=None if not_available_quantity is None else _decimal(not_available_quantity, "not_available_quantity"),
            available_basis=_enum(ops.AvailableBasis, available_basis, "available_basis"),
            encumbrances=[_reported_encumbrance(each, f"encumbrances[{i}]") for i, each in enumerate(encumbrances)],
            raw_record=raw_record,
            provenance=[_provenance(each, f"provenance[{i}]") for i, each in enumerate(provenance)],
            pending=[_reported_pending(each, f"pending[{i}]") for i, each in enumerate(pending)],
            backfill=backfill,
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().RecordHolding, params)

    async def list_custodial_positions(
        self,
        *,
        account_id: str = "",
        include_unresolved: bool = False,
        page_size: int = 0,
        cursor: str = "",
        since: ops.Watermark | None = None,
    ) -> ops.ListCustodialPositionsResult:
        """W2.7: Read custodial positions, and the unresolved holdings beside them (W2.7) (stable)."""
        params = ops.ListCustodialPositionsParams(
            account_id=account_id,
            include_unresolved=include_unresolved,
            page_size=page_size,
            cursor=cursor,
            since=since,
        )
        return await self._operate(self._operations().ListCustodialPositions, params)

    async def list_statements(
        self,
        *,
        account_id: str = "",
        as_of_date: str = "",
        since: ops.Watermark | None = None,
        page_size: int = 0,
        cursor: str = "",
    ) -> ops.ListStatementsResult:
        """W2.9: Read completed statements and their figures (W2.9) (stable)."""
        params = ops.ListStatementsParams(
            account_id=account_id,
            as_of_date=as_of_date,
            since=since,
            page_size=page_size,
            cursor=cursor,
        )
        return await self._operate(self._operations().ListStatements, params)

    async def record_activity(
        self,
        *,
        external_account_id: str = "",
        source: str = "",
        activity: CustodialActivity | None = None,
        acting_for: str | None = None,
    ) -> ops.RecordActivityResult:
        """W2.10: Record one activity (W2.10), as a holding row is recorded (preview)."""
        params = ops.RecordActivityParams(
            external_account_id=external_account_id,
            source=source,
            activity=None if activity is None else _custodial_activity(activity, "activity"),
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().RecordActivity, params)

    async def list_activities(
        self,
        *,
        account_id: str = "",
        trade_date_from: str = "",
        trade_date_to: str = "",
        since: ops.Watermark | None = None,
        page_size: int = 0,
        cursor: str = "",
    ) -> ops.ListActivitiesResult:
        """W2.11: Read an account's activity (W2.11), by trade date, paged (preview)."""
        params = ops.ListActivitiesParams(
            account_id=account_id,
            trade_date_from=trade_date_from,
            trade_date_to=trade_date_to,
            since=since,
            page_size=page_size,
            cursor=cursor,
        )
        return await self._operate(self._operations().ListActivities, params)

    async def resolve_identifier(
        self,
        *,
        identifiers: Sequence[ops.Identifier] = (),
        as_of_ns: int = 0,
        exchange_mic: str = "",
        currency: str = "",
        stated_asset_class: ops.AssetClass | str | None = None,
        stated_currency: str = "",
        stated_description: str = "",
        stated_instrument_type: ops.InstrumentType | str | None = None,
    ) -> ops.ResolveIdentifierResult:
        """W3.1: Reverse resolution: identifiers to an instrument, as of a date (stable)."""
        params = ops.ResolveIdentifierParams(
            identifiers=list(identifiers),
            as_of_ns=as_of_ns,
            exchange_mic=exchange_mic,
            currency=currency,
            stated_asset_class=_enum(ops.AssetClass, stated_asset_class, "stated_asset_class"),
            stated_currency=stated_currency,
            stated_description=stated_description,
            stated_instrument_type=_enum(ops.InstrumentType, stated_instrument_type, "stated_instrument_type"),
        )
        return await self._operate(self._operations().ResolveIdentifier, params)

    async def report_missing_instrument(
        self,
        *,
        source: str = "",
        asset_class: ops.AssetClass | str | None = None,
        identifiers: Sequence[ops.Identifier] = (),
        as_of_ns: int = 0,
        reason: ops.MissReason | str | None = None,
        observed_at_ns: int = 0,
        asset_class_as_reported: ops.AsReported | None = None,
    ) -> ops.Published:
        """W3.2: A resolution missed. A fact, not a request (stable)."""
        params = ops.ReportMissingInstrumentParams(
            source=source,
            asset_class=_enum(ops.AssetClass, asset_class, "asset_class"),
            identifiers=list(identifiers),
            as_of_ns=as_of_ns,
            reason=_enum(ops.MissReason, reason, "reason"),
            observed_at_ns=observed_at_ns,
            asset_class_as_reported=asset_class_as_reported,
        )
        return await self._operate(self._operations().ReportMissingInstrument, params)

    async def resolve_instrument(
        self,
        *,
        instrument_id: str = "",
        as_of_ns: int = 0,
    ) -> ops.ResolveInstrumentResult:
        """W3.6: Forward resolution: an instrument identifier to its record (stable)."""
        params = ops.ResolveInstrumentParams(
            instrument_id=instrument_id,
            as_of_ns=as_of_ns,
        )
        return await self._operate(self._operations().ResolveInstrument, params)

    async def link_external_account(
        self,
        *,
        external_account_id: str = "",
        account_id: str = "",
        new_account_name: str = "",
        new_account_custodian: str = "",
        new_account_type: str = "",
        new_account_owner: str = "",
        new_account_note: str = "",
        acting_for: str | None = None,
    ) -> ops.LinkExternalAccountResult:
        """W6.4: Links an external account a plugin reported, or removes its link (stable)."""
        params = ops.LinkExternalAccountParams(
            external_account_id=external_account_id,
            account_id=account_id,
            new_account_name=new_account_name,
            new_account_custodian=new_account_custodian,
            new_account_type=new_account_type,
            new_account_owner=new_account_owner,
            new_account_note=new_account_note,
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().LinkExternalAccount, params)

    async def read_accounts_for_linking(
        self,
        *,
        acting_for: str | None = None,
    ) -> ops.ReadAccountsForLinkingResult:
        """W6.4: The deployment's accounts, read by a plugin acting for its admin (stable)."""
        params = ops.ReadAccountsForLinkingParams(
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().ReadAccountsForLinking, params)

    async def record_opening_balance(
        self,
        *,
        account_id: str = "",
        as_of_date: str = "",
        sources: Sequence[OpeningSource] = (),
        positions: Sequence[OpeningPosition] = (),
        reason: str = "",
        replaces_entry_id: str = "",
        idempotency_key: str = "",
        acting_for: str | None = None,
    ) -> ops.RecordOpeningBalanceResult:
        """W9.1: RecordOpeningBalance (stable)."""
        params = ops.RecordOpeningBalanceParams(
            account_id=account_id,
            as_of_date=as_of_date,
            sources=[_opening_source(each, f"sources[{i}]") for i, each in enumerate(sources)],
            positions=[_opening_position(each, f"positions[{i}]") for i, each in enumerate(positions)],
            reason=reason,
            replaces_entry_id=replaces_entry_id,
            idempotency_key=idempotency_key,
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().RecordOpeningBalance, params)

    async def record_break(
        self,
        *,
        account_id: str = "",
        break_id: str = "",
        position: PositionKey | None = None,
        figure: ops.FigureKey | None = None,
        category: ops.BreakCategory | str | None = None,
        differences: Sequence[BreakDifference] = (),
        book_watermark: ops.Watermark | None = None,
        street: ops.StreetRecordRef | None = None,
        business_date: str = "",
        candidate_causes: Sequence[BreakCause] = (),
        idempotency_key: str = "",
        acting_for: str | None = None,
    ) -> ops.RecordBreakResult:
        """W9.4: W9.4. A new break, or an open one brought up to date (stable)."""
        params = ops.RecordBreakParams(
            account_id=account_id,
            break_id=break_id,
            **_arm("subject", position=None if position is None else _position_key(position, "position"), figure=figure),
            category=_enum(ops.BreakCategory, category, "category"),
            differences=[_break_difference(each, f"differences[{i}]") for i, each in enumerate(differences)],
            book_watermark=book_watermark,
            street=street,
            business_date=business_date,
            candidate_causes=[_break_cause(each, f"candidate_causes[{i}]") for i, each in enumerate(candidate_causes)],
            idempotency_key=idempotency_key,
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().RecordBreak, params)

    async def record_account_figures(
        self,
        *,
        account_id: str = "",
        business_date: str = "",
        source: ops.StreetRecordRef | None = None,
        agreements: Sequence[AgreementFigures] = (),
        idempotency_key: str = "",
        acting_for: str | None = None,
    ) -> ops.RecordAccountFiguresResult:
        """W9.5: RecordAccountFigures (stable)."""
        params = ops.RecordAccountFiguresParams(
            account_id=account_id,
            business_date=business_date,
            source=source,
            agreements=[_agreement_figures(each, f"agreements[{i}]") for i, each in enumerate(agreements)],
            idempotency_key=idempotency_key,
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().RecordAccountFigures, params)

    async def record_encumbrances(
        self,
        *,
        account_id: str = "",
        business_date: str = "",
        source: ops.StreetRecordRef | None = None,
        positions: Sequence[PositionEncumbrances] = (),
        idempotency_key: str = "",
        acting_for: str | None = None,
    ) -> ops.RecordEncumbrancesResult:
        """W9.15: W9.15. A finding, so the plugin may send it as itself (stable)."""
        params = ops.RecordEncumbrancesParams(
            account_id=account_id,
            business_date=business_date,
            source=source,
            positions=[_position_encumbrances(each, f"positions[{i}]") for i, each in enumerate(positions)],
            idempotency_key=idempotency_key,
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().RecordEncumbrances, params)

    async def handle_break(
        self,
        *,
        account_id: str = "",
        break_id: str = "",
        confirmed_cause: BreakCause | None = None,
        handling: ops.BreakHandling | None = None,
        reason: str = "",
        idempotency_key: str = "",
        acting_for: str | None = None,
    ) -> ops.HandleBreakResult:
        """W9.6: W9.6. For a person (stable)."""
        params = ops.HandleBreakParams(
            account_id=account_id,
            break_id=break_id,
            confirmed_cause=None if confirmed_cause is None else _break_cause(confirmed_cause, "confirmed_cause"),
            handling=handling,
            reason=reason,
            idempotency_key=idempotency_key,
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().HandleBreak, params)

    async def resolve_break(
        self,
        *,
        account_id: str = "",
        break_ids: Sequence[str] = (),
        reason: str = "",
        adjustment: Adjustment | None = None,
        reversal: ops.Reversal | None = None,
        entries: ops.ResolvedByEntries | None = None,
        explanation: str | None = None,
        idempotency_key: str = "",
        acting_for: str | None = None,
    ) -> ops.ResolveBreakResult:
        """W9.7: W9.7. For a person (stable)."""
        params = ops.ResolveBreakParams(
            account_id=account_id,
            break_ids=list(break_ids),
            reason=reason,
            **_arm("resolution", adjustment=None if adjustment is None else _adjustment(adjustment, "adjustment"), reversal=reversal, entries=entries, explanation=explanation),
            idempotency_key=idempotency_key,
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().ResolveBreak, params)

    async def close_breaks_as_cleared(
        self,
        *,
        account_id: str = "",
        break_ids: Sequence[str] = (),
        cleared_at: ops.StreetRecordRef | None = None,
        reason: str = "",
        idempotency_key: str = "",
        acting_for: str | None = None,
    ) -> ops.CloseBreaksAsClearedResult:
        """W9.7: W9.7. Close breaks as cleared, with no entry (stable)."""
        params = ops.CloseBreaksAsClearedParams(
            account_id=account_id,
            break_ids=list(break_ids),
            cleared_at=cleared_at,
            reason=reason,
            idempotency_key=idempotency_key,
            acting_for=_assertion(acting_for),
        )
        return await self._operate(self._operations().CloseBreaksAsCleared, params)

    async def list_positions(
        self,
        *,
        account_id: str = "",
        since: ops.Watermark | None = None,
        business_date: str = "",
        at: ops.Watermark | None = None,
        page_size: int = 0,
        cursor: str = "",
    ) -> ops.ListPositionsResult:
        """W9.10: ListPositions (stable)."""
        params = ops.ListPositionsParams(
            account_id=account_id,
            since=since,
            business_date=business_date,
            at=at,
            page_size=page_size,
            cursor=cursor,
        )
        return await self._operate(self._operations().ListPositions, params)

    async def list_breaks(
        self,
        *,
        account_id: str = "",
        states: Sequence[ops.BreakState | str] = (),
        since: ops.Watermark | None = None,
        page_size: int = 0,
        cursor: str = "",
    ) -> ops.ListBreaksResult:
        """W9.11: ListBreaks (stable)."""
        params = ops.ListBreaksParams(
            account_id=account_id,
            states=[_enum(ops.BreakState, value, "states") for value in states],
            since=since,
            page_size=page_size,
            cursor=cursor,
        )
        return await self._operate(self._operations().ListBreaks, params)

    async def list_account_figures(
        self,
        *,
        account_id: str = "",
        agreement: ops.MarginAgreementRef | None = None,
        from_date: str = "",
        to_date: str = "",
        since: ops.Watermark | None = None,
        at: ops.Watermark | None = None,
        page_size: int = 0,
        cursor: str = "",
    ) -> ops.ListAccountFiguresResult:
        """W9.12: ListAccountFigures (stable)."""
        params = ops.ListAccountFiguresParams(
            account_id=account_id,
            agreement=agreement,
            from_date=from_date,
            to_date=to_date,
            since=since,
            at=at,
            page_size=page_size,
            cursor=cursor,
        )
        return await self._operate(self._operations().ListAccountFigures, params)

    async def list_account_attributes(
        self,
        *,
        account_id: str = "",
        since: ops.Watermark | None = None,
        page_size: int = 0,
        cursor: str = "",
    ) -> ops.ListAccountAttributesResult:
        """W9.14: ListAccountAttributes (stable)."""
        params = ops.ListAccountAttributesParams(
            account_id=account_id,
            since=since,
            page_size=page_size,
            cursor=cursor,
        )
        return await self._operate(self._operations().ListAccountAttributes, params)

    async def receive(
        self,
        *,
        statement_recorded: Callable[[Heard[ops.StatementRecordedEvent]], Awaitable[None]] | None = None,
        custodial_position_updated: Callable[[Heard[ops.CustodialPositionUpdatedEvent]], Awaitable[None]] | None = None,
        position_changed: Callable[[Heard[ops.PositionChangedEvent]], Awaitable[None]] | None = None,
        break_changed: Callable[[Heard[ops.BreakChangedEvent]], Awaitable[None]] | None = None,
        account_figures_recorded: Callable[[Heard[ops.AccountFiguresRecordedEvent]], Awaitable[None]] | None = None,
        account_attribute_changed: Callable[[Heard[ops.AccountAttributeChangedEvent]], Awaitable[None]] | None = None,
        activity_recorded: Callable[[Heard[ops.ActivityRecordedEvent]], Awaitable[None]] | None = None,
        seed: bool = True,
    ) -> None:
        """W4.3: hear the rows given a handler, each change once and in order,
        within the plugin's read scope, until cancelled. Seeded first from the
        store when `seed`; on a gap, a loss or a broken stream, caught up from
        it by each row's query, the handler told by `Heard.caught_up`. A row
        no role of the plugin hears raises NotGranted."""
        await self._receive(
            {
                "StatementRecorded": statement_recorded,
                "CustodialPositionUpdated": custodial_position_updated,
                "PositionChanged": position_changed,
                "BreakChanged": break_changed,
                "AccountFiguresRecorded": account_figures_recorded,
                "AccountAttributeChanged": account_attribute_changed,
                "ActivityRecorded": activity_recorded,
            },
            seed=seed,
        )


@dataclass(frozen=True)
class DeliveredRow:
    """A row a plugin's roles may hear (W4.3), as matrix/scoped.tsv declares
    it: the Delivery's arm carrying it, the path to the account its message
    names (empty when it names none), and the query that reads its changes
    since a watermark, given one account in `account_param`, whose reply
    holds them in `records`, each a record whose last change is in
    `record_journal` and whose account is at `record_account`; a record goes
    into the row's message at `within`, or is the row's message where that
    is empty."""

    name: str
    step: str
    arm: str
    message: Any
    account: tuple[str, ...]
    caught_up_by: str
    account_param: str
    records: str
    within: str
    record_journal: str
    record_account: tuple[str, ...]


#: Every row a plugin's roles may hear, by the arm number of its delivery.
DELIVERED: tuple[DeliveredRow, ...] = (
    DeliveredRow(
        name="StatementRecorded",
        step="W2.5",
        arm="statement_recorded",
        message=ops.StatementRecordedEvent,
        account=("account_id",),
        caught_up_by="list_statements",
        account_param="account_id",
        records="statements",
        within="",
        record_journal="journal",
        record_account=("account_id",),
    ),
    DeliveredRow(
        name="CustodialPositionUpdated",
        step="W2.6",
        arm="custodial_position_updated",
        message=ops.CustodialPositionUpdatedEvent,
        account=("position", "account_id"),
        caught_up_by="list_custodial_positions",
        account_param="account_id",
        records="positions",
        within="position",
        record_journal="last_change",
        record_account=("account_id",),
    ),
    DeliveredRow(
        name="PositionChanged",
        step="W9.8",
        arm="position_changed",
        message=ops.PositionChangedEvent,
        account=("position", "account_id"),
        caught_up_by="list_positions",
        account_param="account_id",
        records="positions",
        within="position",
        record_journal="last_change",
        record_account=("account_id",),
    ),
    DeliveredRow(
        name="BreakChanged",
        step="W9.8",
        arm="break_changed",
        message=ops.BreakChangedEvent,
        account=("break_record", "account_id"),
        caught_up_by="list_breaks",
        account_param="account_id",
        records="breaks",
        within="break_record",
        record_journal="last_change",
        record_account=("account_id",),
    ),
    DeliveredRow(
        name="AccountFiguresRecorded",
        step="W9.8",
        arm="account_figures_recorded",
        message=ops.AccountFiguresRecordedEvent,
        account=("figures", "account_id"),
        caught_up_by="list_account_figures",
        account_param="account_id",
        records="figures",
        within="figures",
        record_journal="last_change",
        record_account=("account_id",),
    ),
    DeliveredRow(
        name="AccountAttributeChanged",
        step="W9.8",
        arm="account_attribute_changed",
        message=ops.AccountAttributeChangedEvent,
        account=("attributes", "account_id"),
        caught_up_by="list_account_attributes",
        account_param="account_id",
        records="attributes",
        within="attributes",
        record_journal="last_change",
        record_account=("account_id",),
    ),
    DeliveredRow(
        name="ActivityRecorded",
        step="W2.12",
        arm="activity_recorded",
        message=ops.ActivityRecordedEvent,
        account=("account_id",),
        caught_up_by="list_activities",
        account_param="account_id",
        records="activities",
        within="",
        record_journal="journal",
        record_account=("account_id",),
    ),
)
