"""What the SDK enforces is what the data dictionary enters.

meridian.bounds is generated by meridian-schema from the dictionary's entries
(boundaries/fields.json) and vendored here beside the wire bindings; the SDK's
checks read it rather than a number of their own
(spec/every-store-publishes-a-versioned-data-dictionary, requirement 15).
Each case is made from the bound, not from a number written here: the bound
accepted, one past it refused in the sidecar's words.
"""

from __future__ import annotations

from decimal import Decimal

import pytest

from meridian import bounds
from meridian.figures import Figure, wire
from meridian.operations import DELIVERED, _decimal
from meridian.receive import catch_up_page


def refused(figures: list[Figure]) -> str:
    with pytest.raises(ValueError) as caught:
        wire(figures)
    return str(caught.value)


def test_a_label_at_its_bound_is_sent_and_one_past_it_refused() -> None:
    most = bounds.PLUGIN_FIGURE_LABEL_LENGTH.most
    assert len(wire([Figure("x" * most, 1)])) == 1
    assert refused([Figure("x" * (most + 1), 1)]) == (
        f"figures[0].label is {most + 1} characters; a label is at most {most}"
    )
    assert bounds.PLUGIN_FIGURE_LABEL_LENGTH.least == 1
    assert refused([Figure("", 1)]) == (
        f"figures[0].label is empty; a label is 1 to {most} characters"
    )


@pytest.mark.parametrize(
    ("bound", "field", "what", "figure"),
    [
        (bounds.PLUGIN_FIGURE_TEXT_LENGTH, "text", "a text", lambda x: Figure("Key", x)),
        (bounds.PLUGIN_FIGURE_WHY_LENGTH, "why", "a why", lambda x: Figure("Key", 1, why=x)),
    ],
)
def test_a_text_and_a_why_at_their_bounds(bound, field, what, figure) -> None:
    assert len(wire([figure("x" * bound.most)])) == 1
    assert refused([figure("x" * (bound.most + 1))]) == (
        f"figures[0].{field} is {bound.most + 1} characters; {what} is at most {bound.most}"
    )


def test_the_most_figures() -> None:
    most = bounds.HEARTBEAT_REQUEST_FIGURES_COUNT.most
    assert len(wire([Figure(f"F{i}", i) for i in range(most)])) == most
    assert refused([Figure(f"F{i}", i) for i in range(most + 1)]) == (
        f"{most + 1} figures; a plugin reports at most {most}"
    )


def test_a_decimal_at_its_scale_and_one_place_past_it() -> None:
    places = bounds.DECIMAL_SCALE.most
    assert _decimal(Decimal("1." + "0" * places), "quantity").scale == places
    with pytest.raises(ValueError, match=f"has {places + 1} decimal places; at most {places}"):
        _decimal(Decimal("1." + "0" * (places + 1)), "quantity")
    with pytest.raises(ValueError, match=f"more than {bounds.DECIMAL_DIGITS} digits"):
        _decimal(10**bounds.DECIMAL_DIGITS, "quantity")
    assert _decimal(10**bounds.DECIMAL_DIGITS - 1, "quantity").scale == 0


def test_every_catch_up_read_asks_for_its_store_s_most() -> None:
    """Each row a plugin hears is caught up by a query whose page size the
    dictionary bounds; a query without one would fail here, not at a gap."""
    for row in DELIVERED:
        bound = getattr(bounds, f"{row.caught_up_by.upper()}_REQUEST_PAGE_SIZE_RANGE")
        assert bound.capped, row.name
        assert catch_up_page(row) == bound.most > 0
